### ISSUE TITLE
Email Address of Area Admin will not be saved

### ISSUE THREAD

**Issue by stueja** [meeting-room-booking-system/mrbs-code#3717] opened 2024-08-10 15:47 UTC
**Describe the bug**
Changing and saving the email address of an area admin has no effect.

**To Reproduce**
1. Go to Rooms
2. Select an area and click the pencil icon
3. Insert an email address in the "area admin email" text box
4. Click save
5. Select the area which was selected before and click the pencil icon

**Expected behavior**
The email address should be as I entered it.

**Screenshots**
![3](https://github.com/user-attachments/assets/baefdcd8-077a-46a8-bb02-a62da1439873)

**Browser details (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 17.5

**Server details (please complete the following information):**
 - MRBS version 1.11.4
 - Web server: nginx/1.22.1
 - OS: Ubuntu 5.15.0 (in docker container)
 - PHP version: 	8.1.20
 - Database used: mariadb.org binary distribution 11.4.2-MariaDB-ubu2404

**Additional context**

**Comment by campbell-m** [comment] 2024-08-10 19:58
I cannot reproduce this.  Are you getting any error messages in your PHP error log?

**Comment by campbell-m** [comment] 2024-08-10 20:04
Or have you added any custom CSS so that email fields are not displayed?

**Comment by campbell-m** [comment] 2024-08-10 20:16
OK, I can reproduce it now using Safari on macOS.  I'll investigate tomorrow.

**Comment by campbell-m** [comment] 2024-08-11 16:32
This is caused by the same problem as #3716, so I am closing it as a duplicate.

**Closed by campbell-m** 2024-08-11 16:32 UTC
Labels: bug

**Comment by campbell-m** [comment] 2024-08-11 17:35
The email address is saved; it's just not displayed by the browser.

**Comment by stueja** [comment] 2024-08-11 18:24
Using a different browser as suggested in #3716 is totally feasible for me. Thanks alot for figuring out!
