### ISSUE TITLE
Week View Single room series

### ISSUE THREAD

**Issue by bladeHP** [meeting-room-booking-system/mrbs-code#3474] opened 2023-07-26 12:04 UTC
HI,
I noticed a couple of bugs in MRBS 1.11.0:
as an administrator user in the weekly view of the single room, when I try to drag a reservation to make a series I fail, if I make a single reservation in the room afterwards it allows me to make the series "dragged" with the mouse.

the second thing is that always in the weekly view of the single room when I make a series dragging with the mouse at the end it brings me back to the daily view of all the rooms. this did not happen in previous versions. 
in fact it seems to me much more comfortable that it remains in the weekly vision of the single room.

Thank you

Marco

**Comment by campbell-m** [comment] 2023-07-26 14:54
I couldn't reproduce these problems in 1.11.3.  In fact I found that resizing bookings didn't work at all!  I've now fixed this in [b529adf](https://github.com/meeting-room-booking-system/mrbs-code/commit/b529adf806737218111480306d09b48e9379770a).  Please could you confirm that everything works as expected when running the latest development code.

**Comment by bladeHP** [comment] 2023-07-27 12:11
sorry, but i can't find these lines in functions_table.inc (fixed b529adf.)
my mrbs version is 1.11.0

$date->setTimestamp($t);
      $classes = get_date_classes($date);
      $result[$i] .= '<th' .
        // Add the date for JavaScript.  Only really necessary for the first row in
        // the week view when not viewing all the rooms, but just add it always.
        ' data-date="' . htmlspecialchars($date->getISODate()) . '"' .
        ((!empty($classes)) ? ' class="' . implode(' ', $classes) . '"' : '') .
        '><a href="' . htmlspecialchars($link) . '">' . htmlspecialchars($text) . "</a></th>\n";
    }

**Comment by campbell-m** [comment] 2023-07-27 13:51
A lot has changed. You will need to download the complete set of files and treat it like a new release.

**Comment by campbell-m** [comment] 2023-07-28 08:55
You can download the code by following the green Code button on [this page](https://github.com/meeting-room-booking-system/mrbs-code).

**Comment by campbell-m** [comment] 2023-10-04 11:35
I haven't heard anything more, so assume this issue has now been resolved.

**Closed by campbell-m** 2023-10-04 11:35 UTC
Labels: bug
