### ISSUE TITLE
Some AD domain users under the unified OU cannot book conferences normally

### ISSUE THREAD

**Issue by wilia** [meeting-room-booking-system/mrbs-code#46] opened 2022-06-23 03:51 UTC
**Describe the bug**
After configuring ldap, some of the domain users under the same department can schedule meetings normally, and some people enter the page to schedule a meeting and appear: "you do not have the necessary rights to view this page.", but when I set the config. inc.php After the '$override_locale = 'zh-cn'' command in inc.php is changed to '$override_locale = 'en'', Meetings can be scheduled as normal

**To Reproduce**
1. Go to 'indes.php'
2. Click on 'entry'
3. prompt:"you do not have the necessary rights to view this page."
4. set the config.inc.php After the '$override_locale = 'zh-cn'' command in inc.php is changed to '$override_locale = 'en'',
5. Go to 'indes.php'
6. Click on 'entry'
7. Meetings can be scheduled as normal

**Expected behavior**
All AD domain users can book meetings normally

**Screenshots**
[error](https://imgtu.com/i/jCllkD)
[AD code](https://imgtu.com/i/jClUnP)

Browser details (please complete the following information):

OS: [e.g. Windows 2008R2]
Browser :[e.g. chrome]
Version [e.g. 49.0]
Server details (please complete the following information):

MRBS version [e.g. 1.10.0]
Web server: [e.g. Apache 2.4.37]
OS: [e.g. Windows 2008R2]
PHP version: [e.g. 7.3.1]
Database used: [e.g. MySQL 5.7.24]

**Comment by campbell-m** [comment] 2022-06-23 04:48
I expect the problem is to do with case sensitivity and case insensitive comparisons of names in different locales.   I recently introduced some fixes for this.  Can you upgrade to the latest set of files in [the main branch](https://github.com/meeting-room-booking-system/mrbs-code) and see if the problem still happens?

**Comment by wilia** [comment] 2022-06-23 06:59
> I expect the problem is to do with case sensitivity and case insensitive comparisons of names in different locales. I recently introduced some fixes for this. Can you upgrade to the latest set of files in [the main branch](https://github.com/meeting-room-booking-system/mrbs-code) and see if the problem still happens?

Re-download the new installation package. After the replacement, I cannot log in to the AD domain, and it prompts "Your session has expired"

**Comment by campbell-m** [comment] 2022-06-23 07:07
Does that happen even if you try and login a second time?

**Comment by wilia** [comment] 2022-06-23 07:23
> Does that happen even if you try and login a second time?

Yes, the same error is reported when changing other AD domain accounts

**Comment by campbell-m** [comment] 2022-06-23 07:27
Are you getting any errors in your PHP error log?

**Comment by wilia** [comment] 2022-06-23 07:37
Even if I change '$override_locale = 'zh-cn'' to '$override_locale = 'en'' in config.inc.php file, it still prompts "Your session has expired"

**Comment by campbell-m** [comment] 2022-06-23 07:49
Are you using MySQL or PostgreSQL?

**Comment by wilia** [comment] 2022-06-23 07:53
> Are you using MySQL or PostgreSQL?

MariaDB 10.3.12

**Comment by wilia** [comment] 2022-06-23 08:44
> Can you try re-uploading all the files in all the directories please, just to make sure that everything is up to date?

I re-downloaded the complete package and replaced it. The configuration file only retains the configuration code related to connecting to the database and ldap, and the problem remains

**Comment by campbell-m** [comment] 2022-06-23 08:58
Can you try emptying the mrbs_sessions table? In other words keep the table but delete all the rows?

**Comment by wilia** [comment] 2022-06-23 09:40
> mrbs_sessions table

After clearing all the data in the mrbs_sessions table, the login still displays "Your session has expired"

**Comment by wilia** [comment] 2022-06-23 10:09
Now even if I roll back the mrbs version, it shows "Your session has expired"

**Comment by wilia** [comment] 2022-06-23 10:21
> Can you try emptying the mrbs_sessions table? In other words keep the table but delete all the rows?

I found the reason, "$cookie_path_override=''" is wrong, after modification, you can log in normally, but some users can still book meetings normally, and some users book a meeting and display "you do not have the necessary rights to view this page. "

**Comment by campbell-m** [comment] 2022-06-23 10:24
And does this still happen with the latest version of the code?

**Comment by wilia** [comment] 2022-06-23 10:27
> And does this still happen with the latest version of the code?

Yes, after updating the latest code, the phenomenon is still there. When '$override_locale = 'zh-cn'' is configured, the meeting cannot be booked, and "you do not have the necessary rights to view this page." is displayed, and the configuration is '$override_locale = 'en'' can book a meeting normally

**Comment by campbell-m** [comment] 2022-06-23 18:08
Can you give me an example of a username that has this problem please?  If it's confidential you could send me a private message, though I'm not sure that you can do this on GitHub.  If not, you may need to do it via [Sourceforge](https://sourceforge.net/projects/mrbs/).

**Comment by campbell-m** [comment] 2022-06-24 05:38
You can email me at cimorrison at users dot sourceforge dot net.

**Comment by wilia** [comment] 2022-06-24 07:07
> users dot sourceforge dot net.

I don't understand, can I send it to your email?sourceforge website I tried many times and couldn't complete the registration

**Comment by campbell-m** [comment] 2022-06-24 07:29
Replace "at" by "@" and "dot" by "."

**Comment by wilia** [comment] 2022-06-24 08:25
> Replace "at" by "@" and "dot" by "."

EMAIL has been sent

**Comment by campbell-m** [comment] 2022-06-24 09:55
Thanks. I have got your email. I will look at it later.

**Comment by campbell-m** [comment] 2022-06-24 14:51
I have now fixed this and you can download the latest code from [the main branch](https://github.com/meeting-room-booking-system/mrbs-code).

Interestingly I think there's a bug in the PHP function `strcasecmp()` which fails to return 0 for two identical strings when the locale is set to 'zh-CN'.  I will report it to the PHP when I can reproduce it with two strings that are not confidential.

**Comment by campbell-m** [comment] 2022-06-25 07:14
> Interestingly I think there's a bug in the PHP function `strcasecmp()` which fails to return 0 for two identical strings when the locale is set to 'zh-CN'. I will report it to the PHP when I can reproduce it with two strings that are not confidential.

No, I was mistaken: `strcasecmp()` works as expected.  It was my code at fault.

**Closed by campbell-m** 2022-06-25 07:14 UTC
Labels: bug
